/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace QuadraticFunding {
  export type ParticipantStruct = {
    trustScore: BigNumberish;
    expiresAt: BigNumberish;
    exists: boolean;
  };

  export type ParticipantStructOutput = [
    trustScore: bigint,
    expiresAt: bigint,
    exists: boolean
  ] & { trustScore: bigint; expiresAt: bigint; exists: boolean };

  export type ProjectStruct = {
    recipient: AddressLike;
    totalContributions: BigNumberish;
    sumOfSqrtContributions: BigNumberish;
    exists: boolean;
    withdrawn: boolean;
    matchedAmount: BigNumberish;
  };

  export type ProjectStructOutput = [
    recipient: string,
    totalContributions: bigint,
    sumOfSqrtContributions: bigint,
    exists: boolean,
    withdrawn: boolean,
    matchedAmount: bigint
  ] & {
    recipient: string;
    totalContributions: bigint;
    sumOfSqrtContributions: bigint;
    exists: boolean;
    withdrawn: boolean;
    matchedAmount: bigint;
  };
}

export interface QuadraticFundingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ATTESTOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "TREASURER_ROLE"
      | "castVote"
      | "closeRound"
      | "contributionOf"
      | "distributedMatching"
      | "fundMatchingPool"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "matchFunds"
      | "matchesComputed"
      | "matchingPool"
      | "matchingWeight"
      | "minTrustScore"
      | "participantInfo"
      | "poolFunds"
      | "previewMatch"
      | "projectCount"
      | "projectDetails"
      | "recordParticipant"
      | "registerProject"
      | "renounceRole"
      | "revokeRole"
      | "rgu"
      | "roundClosed"
      | "setMinTrustScore"
      | "supportsInterface"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsWithdrawn"
      | "MatchingCalculated"
      | "MatchingPoolFunded"
      | "MinTrustScoreUpdated"
      | "ParticipantRecorded"
      | "ProjectRegistered"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "RoundClosed"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ATTESTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributionOf",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributedMatching",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundMatchingPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matchFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matchesComputed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matchingPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matchingWeight",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minTrustScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "participantInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "previewMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projectDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordParticipant",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "rgu", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "roundClosed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinTrustScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ATTESTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeRound", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributionOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributedMatching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundMatchingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matchFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "matchesComputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchingWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTrustScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participantInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rgu", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roundClosed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinTrustScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchingCalculatedEvent {
  export type InputTuple = [projectId: BigNumberish, matchAmount: BigNumberish];
  export type OutputTuple = [projectId: bigint, matchAmount: bigint];
  export interface OutputObject {
    projectId: bigint;
    matchAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchingPoolFundedEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    totalPool: BigNumberish
  ];
  export type OutputTuple = [from: string, amount: bigint, totalPool: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
    totalPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinTrustScoreUpdatedEvent {
  export type InputTuple = [minTrustScore: BigNumberish];
  export type OutputTuple = [minTrustScore: bigint];
  export interface OutputObject {
    minTrustScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantRecordedEvent {
  export type InputTuple = [
    user: AddressLike,
    trustScore: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    trustScore: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    user: string;
    trustScore: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectRegisteredEvent {
  export type InputTuple = [projectId: BigNumberish, recipient: AddressLike];
  export type OutputTuple = [projectId: bigint, recipient: string];
  export interface OutputObject {
    projectId: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoundClosedEvent {
  export type InputTuple = [atBlock: BigNumberish];
  export type OutputTuple = [atBlock: bigint];
  export interface OutputObject {
    atBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    voter: AddressLike,
    amount: BigNumberish,
    totalContribution: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    voter: string,
    amount: bigint,
    totalContribution: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    voter: string;
    amount: bigint;
    totalContribution: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QuadraticFunding extends BaseContract {
  connect(runner?: ContractRunner | null): QuadraticFunding;
  waitForDeployment(): Promise<this>;

  interface: QuadraticFundingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ATTESTOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  TREASURER_ROLE: TypedContractMethod<[], [string], "view">;

  castVote: TypedContractMethod<
    [projectId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  closeRound: TypedContractMethod<[], [void], "nonpayable">;

  contributionOf: TypedContractMethod<
    [projectId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  distributedMatching: TypedContractMethod<[], [bigint], "view">;

  fundMatchingPool: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  matchFunds: TypedContractMethod<[], [void], "nonpayable">;

  matchesComputed: TypedContractMethod<[], [boolean], "view">;

  matchingPool: TypedContractMethod<[], [bigint], "view">;

  matchingWeight: TypedContractMethod<[], [bigint], "view">;

  minTrustScore: TypedContractMethod<[], [bigint], "view">;

  participantInfo: TypedContractMethod<
    [user: AddressLike],
    [QuadraticFunding.ParticipantStructOutput],
    "view"
  >;

  poolFunds: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  previewMatch: TypedContractMethod<
    [projectId: BigNumberish],
    [bigint],
    "view"
  >;

  projectCount: TypedContractMethod<[], [bigint], "view">;

  projectDetails: TypedContractMethod<
    [projectId: BigNumberish],
    [QuadraticFunding.ProjectStructOutput],
    "view"
  >;

  recordParticipant: TypedContractMethod<
    [user: AddressLike, trustScore: BigNumberish, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerProject: TypedContractMethod<
    [recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  rgu: TypedContractMethod<[], [string], "view">;

  roundClosed: TypedContractMethod<[], [boolean], "view">;

  setMinTrustScore: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  withdraw: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ATTESTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TREASURER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [projectId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "closeRound"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contributionOf"
  ): TypedContractMethod<
    [projectId: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "distributedMatching"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundMatchingPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "matchFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "matchesComputed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "matchingPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matchingWeight"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minTrustScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "participantInfo"
  ): TypedContractMethod<
    [user: AddressLike],
    [QuadraticFunding.ParticipantStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolFunds"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "previewMatch"
  ): TypedContractMethod<[projectId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "projectCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "projectDetails"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [QuadraticFunding.ProjectStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordParticipant"
  ): TypedContractMethod<
    [user: AddressLike, trustScore: BigNumberish, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerProject"
  ): TypedContractMethod<[recipient: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rgu"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "roundClosed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setMinTrustScore"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MatchingCalculated"
  ): TypedContractEvent<
    MatchingCalculatedEvent.InputTuple,
    MatchingCalculatedEvent.OutputTuple,
    MatchingCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchingPoolFunded"
  ): TypedContractEvent<
    MatchingPoolFundedEvent.InputTuple,
    MatchingPoolFundedEvent.OutputTuple,
    MatchingPoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "MinTrustScoreUpdated"
  ): TypedContractEvent<
    MinTrustScoreUpdatedEvent.InputTuple,
    MinTrustScoreUpdatedEvent.OutputTuple,
    MinTrustScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantRecorded"
  ): TypedContractEvent<
    ParticipantRecordedEvent.InputTuple,
    ParticipantRecordedEvent.OutputTuple,
    ParticipantRecordedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectRegistered"
  ): TypedContractEvent<
    ProjectRegisteredEvent.InputTuple,
    ProjectRegisteredEvent.OutputTuple,
    ProjectRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoundClosed"
  ): TypedContractEvent<
    RoundClosedEvent.InputTuple,
    RoundClosedEvent.OutputTuple,
    RoundClosedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "FundsWithdrawn(uint256,address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "MatchingCalculated(uint256,uint256)": TypedContractEvent<
      MatchingCalculatedEvent.InputTuple,
      MatchingCalculatedEvent.OutputTuple,
      MatchingCalculatedEvent.OutputObject
    >;
    MatchingCalculated: TypedContractEvent<
      MatchingCalculatedEvent.InputTuple,
      MatchingCalculatedEvent.OutputTuple,
      MatchingCalculatedEvent.OutputObject
    >;

    "MatchingPoolFunded(address,uint256,uint256)": TypedContractEvent<
      MatchingPoolFundedEvent.InputTuple,
      MatchingPoolFundedEvent.OutputTuple,
      MatchingPoolFundedEvent.OutputObject
    >;
    MatchingPoolFunded: TypedContractEvent<
      MatchingPoolFundedEvent.InputTuple,
      MatchingPoolFundedEvent.OutputTuple,
      MatchingPoolFundedEvent.OutputObject
    >;

    "MinTrustScoreUpdated(uint256)": TypedContractEvent<
      MinTrustScoreUpdatedEvent.InputTuple,
      MinTrustScoreUpdatedEvent.OutputTuple,
      MinTrustScoreUpdatedEvent.OutputObject
    >;
    MinTrustScoreUpdated: TypedContractEvent<
      MinTrustScoreUpdatedEvent.InputTuple,
      MinTrustScoreUpdatedEvent.OutputTuple,
      MinTrustScoreUpdatedEvent.OutputObject
    >;

    "ParticipantRecorded(address,uint256,uint256)": TypedContractEvent<
      ParticipantRecordedEvent.InputTuple,
      ParticipantRecordedEvent.OutputTuple,
      ParticipantRecordedEvent.OutputObject
    >;
    ParticipantRecorded: TypedContractEvent<
      ParticipantRecordedEvent.InputTuple,
      ParticipantRecordedEvent.OutputTuple,
      ParticipantRecordedEvent.OutputObject
    >;

    "ProjectRegistered(uint256,address)": TypedContractEvent<
      ProjectRegisteredEvent.InputTuple,
      ProjectRegisteredEvent.OutputTuple,
      ProjectRegisteredEvent.OutputObject
    >;
    ProjectRegistered: TypedContractEvent<
      ProjectRegisteredEvent.InputTuple,
      ProjectRegisteredEvent.OutputTuple,
      ProjectRegisteredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "RoundClosed(uint256)": TypedContractEvent<
      RoundClosedEvent.InputTuple,
      RoundClosedEvent.OutputTuple,
      RoundClosedEvent.OutputObject
    >;
    RoundClosed: TypedContractEvent<
      RoundClosedEvent.InputTuple,
      RoundClosedEvent.OutputTuple,
      RoundClosedEvent.OutputObject
    >;

    "VoteCast(uint256,address,uint256,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
